import { Dimensions, StyleSheet } from "react-native";
import { cxlxrs } from "../../constants/Colors";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: cxlxrs.white,
  },
  modal: {
    width: "100%",
    height: Dimensions.get("screen").height,
    backgroundColor: cxlxrs.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 30,
  },
  header: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    paddingTop: 40,
    paddingBottom: 15,
    paddingLeft: 20,
    paddingRight: 10,
    minHeight: 80,
    backgroundColor: cxlxrs.white,
    justifyContent: "space-between",
  },
  circle: {
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    borderRadius: 20,
    marginLeft: 5,
    elevation: 2,
    backgroundColor: cxlxrs.white,
  },
  routeTitle: {
    color: "#111111",
    fontSize: 16,
    letterSpacing: 1,
  },
  title: {
    color: "#42414C",
    fontSize: 16,
    marginBottom: 5,
    marginLeft: -2,
    marginBottom: 1,
    fontFamily: "FiraCode-SemiBold",
    textAlign: "center",
  },

  customDialogTitle: {
    paddingVertical: 5,
    borderBottomColor: "#44444444",
    borderBottomWidth: 1,
    width: "100%",
    marginBottom: 10,
  },
  customDialogBody: {
    // alignSelf: "center",
    flex: 1,
    // justifyContent: "center",
  },
  modalTextButton: {
    marginVertical: 3,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  modalText: {
    color: "#111111",
    fontWeight: "600",
    fontSize: 15,
  },
  focusedText: {
    color: "#006eff",
    fontSize: 9,
    fontWeight: "bold",
    letterSpacing: 1,
    marginTop: 5,
    textTransform: "uppercase",
    textAlign: "center",
  },
  noPostContainerWrapper: {
    minHeight: 150,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  noPostContainer: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  noPost: {
    position: "absolute",
    fontWeight: "100",
  },
  listReels: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingBottom: 20,
  },
  moreModalContainer: {
    position: "absolute",
    zIndex: 5,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: "flex-end",
    backgroundColor: "transparent",
    paddingTop: 85,
  },
  listReels: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingBottom: 20,
  },
  buttonContainer: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "transparent",
  },
  button: {
    flexDirection: "row",
    backgroundColor: "#006eff",
    elevation: 2,
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    width: 50,
    borderRadius: 25,
  },
  buttonText: {
    color: "#111111",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
    marginRight: 5,
  },
});
