export const ActionTypes = {
  SET_TOGGLE_SHOW_BOTTOM_NAVBAR: "SET_TOGGLE_SHOW_BOTTOM_NAVBAR",
  SET_CHAT_FONT: "SET_CHAT_FONT",
  SET_CHAT_FONT_SIZE: "SET_CHAT_FONT_SIZE",
  SET_CHAT_BACKGROUND: "SET_CHAT_BACKGROUND",
  SET_COLORS: "SET_COLORS",
};
